package com.twitminer.dao.arraylist;

import java.util.ArrayList;
import java.util.List;

import com.twitminer.beans.StopWord;
import com.twitminer.dao.StopWordDAO;

public class ArrayListStopWordDAO extends StopWordDAO {

	ArrayList<StopWord> stopWords;
	
	public ArrayListStopWordDAO () {
		stopWords = new ArrayList<StopWord>();
		StopWord tempStop;
		tempStop = new StopWord();
		tempStop.setStopWordId(1);
		tempStop.setStopWord("able");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(2);
		tempStop.setStopWord("about");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(3);
		tempStop.setStopWord("above");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(4);
		tempStop.setStopWord("abroad");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(5);
		tempStop.setStopWord("according");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(6);
		tempStop.setStopWord("accordingly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(7);
		tempStop.setStopWord("across");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(8);
		tempStop.setStopWord("actually");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(9);
		tempStop.setStopWord("adj");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(10);
		tempStop.setStopWord("after");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(11);
		tempStop.setStopWord("afterwards");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(12);
		tempStop.setStopWord("again");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(13);
		tempStop.setStopWord("against");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(14);
		tempStop.setStopWord("ago");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(15);
		tempStop.setStopWord("ahead");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(16);
		tempStop.setStopWord("ain\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(17);
		tempStop.setStopWord("all");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(18);
		tempStop.setStopWord("allow");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(19);
		tempStop.setStopWord("allows");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(20);
		tempStop.setStopWord("almost");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(21);
		tempStop.setStopWord("alone");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(22);
		tempStop.setStopWord("along");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(23);
		tempStop.setStopWord("alongside");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(24);
		tempStop.setStopWord("already");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(25);
		tempStop.setStopWord("also");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(26);
		tempStop.setStopWord("although");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(27);
		tempStop.setStopWord("always");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(28);
		tempStop.setStopWord("am");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(29);
		tempStop.setStopWord("amid");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(30);
		tempStop.setStopWord("amidst");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(31);
		tempStop.setStopWord("an");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(32);
		tempStop.setStopWord("and");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(33);
		tempStop.setStopWord("another");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(34);
		tempStop.setStopWord("any");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(35);
		tempStop.setStopWord("anybody");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(36);
		tempStop.setStopWord("anyhow");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(37);
		tempStop.setStopWord("anyone");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(38);
		tempStop.setStopWord("anything");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(39);
		tempStop.setStopWord("anyway");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(40);
		tempStop.setStopWord("anyways");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(41);
		tempStop.setStopWord("anywhere");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(42);
		tempStop.setStopWord("apart");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(43);
		tempStop.setStopWord("appear");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(44);
		tempStop.setStopWord("appreciate");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(45);
		tempStop.setStopWord("appropriate");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(46);
		tempStop.setStopWord("are");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(47);
		tempStop.setStopWord("aren\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(48);
		tempStop.setStopWord("around");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(49);
		tempStop.setStopWord("as");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(50);
		tempStop.setStopWord("a\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(51);
		tempStop.setStopWord("aside");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(52);
		tempStop.setStopWord("ask");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(53);
		tempStop.setStopWord("asking");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(54);
		tempStop.setStopWord("associated");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(55);
		tempStop.setStopWord("at");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(56);
		tempStop.setStopWord("available");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(57);
		tempStop.setStopWord("away");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(58);
		tempStop.setStopWord("awfully");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(59);
		tempStop.setStopWord("back");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(60);
		tempStop.setStopWord("backward");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(61);
		tempStop.setStopWord("backwards");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(62);
		tempStop.setStopWord("be");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(63);
		tempStop.setStopWord("became");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(64);
		tempStop.setStopWord("because");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(65);
		tempStop.setStopWord("become");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(66);
		tempStop.setStopWord("becomes");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(67);
		tempStop.setStopWord("becoming");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(68);
		tempStop.setStopWord("been");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(69);
		tempStop.setStopWord("before");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(70);
		tempStop.setStopWord("beforehand");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(71);
		tempStop.setStopWord("begin");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(72);
		tempStop.setStopWord("behind");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(73);
		tempStop.setStopWord("being");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(74);
		tempStop.setStopWord("believe");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(75);
		tempStop.setStopWord("below");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(76);
		tempStop.setStopWord("beside");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(77);
		tempStop.setStopWord("besides");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(78);
		tempStop.setStopWord("best");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(79);
		tempStop.setStopWord("better");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(80);
		tempStop.setStopWord("between");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(81);
		tempStop.setStopWord("beyond");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(82);
		tempStop.setStopWord("both");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(83);
		tempStop.setStopWord("brief");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(84);
		tempStop.setStopWord("but");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(85);
		tempStop.setStopWord("by");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(86);
		tempStop.setStopWord("came");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(87);
		tempStop.setStopWord("can");
		stopWords.add(tempStop);
/*		tempStop = new StopWord();
		tempStop.setStopWordId(88);
		tempStop.setStopWord("cannot");
		stopWords.add(tempStop);*/
		tempStop = new StopWord();
		tempStop.setStopWordId(89);
		tempStop.setStopWord("cant");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(90);
		tempStop.setStopWord("can\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(91);
		tempStop.setStopWord("caption");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(92);
		tempStop.setStopWord("cause");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(93);
		tempStop.setStopWord("causes");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(94);
		tempStop.setStopWord("certain");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(95);
		tempStop.setStopWord("certainly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(96);
		tempStop.setStopWord("changes");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(97);
		tempStop.setStopWord("clearly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(98);
		tempStop.setStopWord("c\'mon");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(99);
		tempStop.setStopWord("co");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(100);
		tempStop.setStopWord("co.");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(101);
		tempStop.setStopWord("com");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(102);
		tempStop.setStopWord("come");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(103);
		tempStop.setStopWord("comes");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(104);
		tempStop.setStopWord("concerning");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(105);
		tempStop.setStopWord("consequently");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(106);
		tempStop.setStopWord("consider");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(107);
		tempStop.setStopWord("considering");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(108);
		tempStop.setStopWord("contain");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(109);
		tempStop.setStopWord("containing");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(110);
		tempStop.setStopWord("contains");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(111);
		tempStop.setStopWord("corresponding");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(112);
		tempStop.setStopWord("could");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(113);
		tempStop.setStopWord("couldn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(114);
		tempStop.setStopWord("course");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(115);
		tempStop.setStopWord("c\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(116);
		tempStop.setStopWord("currently");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(117);
		tempStop.setStopWord("date");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(118);
		tempStop.setStopWord("daren\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(119);
		tempStop.setStopWord("definitely");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(120);
		tempStop.setStopWord("described");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(121);
		tempStop.setStopWord("despite");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(122);
		tempStop.setStopWord("did");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(123);
		tempStop.setStopWord("didn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(124);
		tempStop.setStopWord("different");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(125);
		tempStop.setStopWord("directly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(126);
		tempStop.setStopWord("do");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(127);
		tempStop.setStopWord("does");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(128);
		tempStop.setStopWord("doesn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(129);
		tempStop.setStopWord("doing");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(130);
		tempStop.setStopWord("done");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(131);
		tempStop.setStopWord("don\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(132);
		tempStop.setStopWord("down");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(133);
		tempStop.setStopWord("downwards");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(134);
		tempStop.setStopWord("during");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(135);
		tempStop.setStopWord("each");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(136);
		tempStop.setStopWord("edu");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(137);
		tempStop.setStopWord("eg");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(138);
		tempStop.setStopWord("eight");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(139);
		tempStop.setStopWord("eighty");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(140);
		tempStop.setStopWord("either");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(141);
		tempStop.setStopWord("else");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(142);
		tempStop.setStopWord("elsewhere");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(143);
		tempStop.setStopWord("end");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(144);
		tempStop.setStopWord("ending");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(145);
		tempStop.setStopWord("enough");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(146);
		tempStop.setStopWord("entirely");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(147);
		tempStop.setStopWord("especially");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(148);
		tempStop.setStopWord("et");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(149);
		tempStop.setStopWord("etc");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(150);
		tempStop.setStopWord("even");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(151);
		tempStop.setStopWord("ever");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(152);
		tempStop.setStopWord("evermore");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(153);
		tempStop.setStopWord("every");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(154);
		tempStop.setStopWord("everybody");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(155);
		tempStop.setStopWord("everyone");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(156);
		tempStop.setStopWord("everything");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(157);
		tempStop.setStopWord("everywhere");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(158);
		tempStop.setStopWord("ex");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(159);
		tempStop.setStopWord("exactly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(160);
		tempStop.setStopWord("example");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(161);
		tempStop.setStopWord("except");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(162);
		tempStop.setStopWord("fairly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(163);
		tempStop.setStopWord("far");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(164);
		tempStop.setStopWord("farther");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(165);
		tempStop.setStopWord("few");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(166);
		tempStop.setStopWord("fewer");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(167);
		tempStop.setStopWord("fifth");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(168);
		tempStop.setStopWord("first");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(169);
		tempStop.setStopWord("five");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(170);
		tempStop.setStopWord("followed");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(171);
		tempStop.setStopWord("following");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(172);
		tempStop.setStopWord("follows");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(173);
		tempStop.setStopWord("for");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(174);
		tempStop.setStopWord("forever");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(175);
		tempStop.setStopWord("former");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(176);
		tempStop.setStopWord("formerly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(177);
		tempStop.setStopWord("forth");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(178);
		tempStop.setStopWord("forward");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(179);
		tempStop.setStopWord("found");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(180);
		tempStop.setStopWord("four");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(181);
		tempStop.setStopWord("from");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(182);
		tempStop.setStopWord("further");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(183);
		tempStop.setStopWord("furthermore");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(184);
		tempStop.setStopWord("get");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(185);
		tempStop.setStopWord("gets");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(186);
		tempStop.setStopWord("getting");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(187);
		tempStop.setStopWord("given");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(188);
		tempStop.setStopWord("gives");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(189);
		tempStop.setStopWord("go");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(190);
		tempStop.setStopWord("goes");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(191);
		tempStop.setStopWord("going");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(192);
		tempStop.setStopWord("gone");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(193);
		tempStop.setStopWord("got");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(194);
		tempStop.setStopWord("gotten");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(195);
		tempStop.setStopWord("greetings");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(196);
		tempStop.setStopWord("had");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(197);
		tempStop.setStopWord("hadn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(198);
		tempStop.setStopWord("half");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(199);
		tempStop.setStopWord("happens");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(200);
		tempStop.setStopWord("hardly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(201);
		tempStop.setStopWord("has");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(202);
		tempStop.setStopWord("hasn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(203);
		tempStop.setStopWord("have");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(204);
		tempStop.setStopWord("haven\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(205);
		tempStop.setStopWord("having");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(206);
		tempStop.setStopWord("he");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(207);
		tempStop.setStopWord("he\'d");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(208);
		tempStop.setStopWord("he\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(209);
		tempStop.setStopWord("hello");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(210);
		tempStop.setStopWord("help");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(211);
		tempStop.setStopWord("hence");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(212);
		tempStop.setStopWord("her");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(213);
		tempStop.setStopWord("here");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(214);
		tempStop.setStopWord("hereafter");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(215);
		tempStop.setStopWord("hereby");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(216);
		tempStop.setStopWord("herein");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(217);
		tempStop.setStopWord("here\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(218);
		tempStop.setStopWord("hereupon");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(219);
		tempStop.setStopWord("hers");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(220);
		tempStop.setStopWord("herself");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(221);
		tempStop.setStopWord("he\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(222);
		tempStop.setStopWord("hi");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(223);
		tempStop.setStopWord("him");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(224);
		tempStop.setStopWord("himself");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(225);
		tempStop.setStopWord("his");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(226);
		tempStop.setStopWord("hither");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(227);
		tempStop.setStopWord("hopefully");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(228);
		tempStop.setStopWord("how");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(229);
		tempStop.setStopWord("howbeit");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(230);
		tempStop.setStopWord("however");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(231);
		tempStop.setStopWord("hundred");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(232);
		tempStop.setStopWord("i\'d");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(233);
		tempStop.setStopWord("ie");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(234);
		tempStop.setStopWord("if");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(235);
		tempStop.setStopWord("ignored");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(236);
		tempStop.setStopWord("i\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(237);
		tempStop.setStopWord("i\'m");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(238);
		tempStop.setStopWord("immediate");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(239);
		tempStop.setStopWord("in");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(240);
		tempStop.setStopWord("inasmuch");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(241);
		tempStop.setStopWord("inc");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(242);
		tempStop.setStopWord("inc.");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(243);
		tempStop.setStopWord("indeed");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(244);
		tempStop.setStopWord("indicate");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(245);
		tempStop.setStopWord("indicated");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(246);
		tempStop.setStopWord("indicates");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(247);
		tempStop.setStopWord("inner");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(248);
		tempStop.setStopWord("inside");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(249);
		tempStop.setStopWord("insofar");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(250);
		tempStop.setStopWord("instead");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(251);
		tempStop.setStopWord("into");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(252);
		tempStop.setStopWord("inward");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(253);
		tempStop.setStopWord("is");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(254);
		tempStop.setStopWord("isn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(255);
		tempStop.setStopWord("it");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(256);
		tempStop.setStopWord("it\'d");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(257);
		tempStop.setStopWord("it\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(258);
		tempStop.setStopWord("its");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(259);
		tempStop.setStopWord("it\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(260);
		tempStop.setStopWord("itself");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(261);
		tempStop.setStopWord("i\'ve");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(262);
		tempStop.setStopWord("just");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(263);
		tempStop.setStopWord("k");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(264);
		tempStop.setStopWord("keep");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(265);
		tempStop.setStopWord("keeps");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(266);
		tempStop.setStopWord("kept");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(267);
		tempStop.setStopWord("know");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(268);
		tempStop.setStopWord("last");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(269);
		tempStop.setStopWord("lately");
		stopWords.add(tempStop);
		
		tempStop = new StopWord();
		tempStop.setStopWordId(630);
		tempStop.setStopWord("lol");
		stopWords.add(tempStop);
		
		tempStop = new StopWord();
		tempStop.setStopWordId(270);
		tempStop.setStopWord("knows");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(271);
		tempStop.setStopWord("later");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(272);
		tempStop.setStopWord("latter");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(273);
		tempStop.setStopWord("latterly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(274);
		tempStop.setStopWord("least");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(275);
		tempStop.setStopWord("less");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(276);
		tempStop.setStopWord("lest");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(277);
		tempStop.setStopWord("let");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(278);
		tempStop.setStopWord("let\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(279);
		tempStop.setStopWord("like");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(280);
		tempStop.setStopWord("liked");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(281);
		tempStop.setStopWord("likely");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(282);
		tempStop.setStopWord("likewise");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(283);
		tempStop.setStopWord("little");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(284);
		tempStop.setStopWord("look");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(285);
		tempStop.setStopWord("looking");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(286);
		tempStop.setStopWord("looks");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(287);
		tempStop.setStopWord("low");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(288);
		tempStop.setStopWord("lower");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(289);
		tempStop.setStopWord("ltd");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(290);
		tempStop.setStopWord("made");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(291);
		tempStop.setStopWord("mainly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(292);
		tempStop.setStopWord("make");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(293);
		tempStop.setStopWord("makes");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(294);
		tempStop.setStopWord("many");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(295);
		tempStop.setStopWord("may");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(296);
		tempStop.setStopWord("maybe");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(297);
		tempStop.setStopWord("mayn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(298);
		tempStop.setStopWord("me");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(299);
		tempStop.setStopWord("mean");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(300);
		tempStop.setStopWord("meantime");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(301);
		tempStop.setStopWord("meanwhile");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(302);
		tempStop.setStopWord("merely");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(303);
		tempStop.setStopWord("might");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(304);
		tempStop.setStopWord("mightn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(305);
		tempStop.setStopWord("mine");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(306);
		tempStop.setStopWord("minus");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(307);
		tempStop.setStopWord("miss");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(308);
		tempStop.setStopWord("more");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(309);
		tempStop.setStopWord("moreover");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(310);
		tempStop.setStopWord("most");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(311);
		tempStop.setStopWord("mostly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(312);
		tempStop.setStopWord("mr");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(313);
		tempStop.setStopWord("mrs");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(314);
		tempStop.setStopWord("much");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(315);
		tempStop.setStopWord("must");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(316);
		tempStop.setStopWord("mustn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(317);
		tempStop.setStopWord("my");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(318);
		tempStop.setStopWord("myself");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(319);
		tempStop.setStopWord("name");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(320);
		tempStop.setStopWord("namely");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(321);
		tempStop.setStopWord("nd");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(322);
		tempStop.setStopWord("near");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(323);
		tempStop.setStopWord("nearly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(324);
		tempStop.setStopWord("necessary");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(325);
		tempStop.setStopWord("need");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(326);
		tempStop.setStopWord("needn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(327);
		tempStop.setStopWord("needs");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(328);
		tempStop.setStopWord("neither");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(329);
		tempStop.setStopWord("never");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(330);
		tempStop.setStopWord("neverf");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(331);
		tempStop.setStopWord("neverless");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(332);
		tempStop.setStopWord("nevertheless");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(333);
		tempStop.setStopWord("new");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(334);
		tempStop.setStopWord("next");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(335);
		tempStop.setStopWord("nine");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(336);
		tempStop.setStopWord("ninety");
		stopWords.add(tempStop);
/*		tempStop = new StopWord();
		tempStop.setStopWordId(337);
		tempStop.setStopWord("no");
		stopWords.add(tempStop);*/
		tempStop = new StopWord();
		tempStop.setStopWordId(338);
		tempStop.setStopWord("nobody");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(339);
		tempStop.setStopWord("non");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(340);
		tempStop.setStopWord("none");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(341);
		tempStop.setStopWord("nonetheless");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(342);
		tempStop.setStopWord("noone");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(343);
		tempStop.setStopWord("no-one");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(344);
		tempStop.setStopWord("nor");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(345);
		tempStop.setStopWord("normally");
		stopWords.add(tempStop);
/*		tempStop = new StopWord();
		tempStop.setStopWordId(346);
		tempStop.setStopWord("not");
		stopWords.add(tempStop);*/
		tempStop = new StopWord();
		tempStop.setStopWordId(347);
		tempStop.setStopWord("nothing");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(348);
		tempStop.setStopWord("notwithstanding");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(349);
		tempStop.setStopWord("novel");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(350);
		tempStop.setStopWord("now");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(351);
		tempStop.setStopWord("nowhere");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(352);
		tempStop.setStopWord("obviously");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(353);
		tempStop.setStopWord("of");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(354);
		tempStop.setStopWord("off");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(355);
		tempStop.setStopWord("often");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(356);
		tempStop.setStopWord("oh");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(357);
		tempStop.setStopWord("ok");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(358);
		tempStop.setStopWord("okay");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(359);
		tempStop.setStopWord("old");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(360);
		tempStop.setStopWord("on");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(361);
		tempStop.setStopWord("once");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(362);
		tempStop.setStopWord("one");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(363);
		tempStop.setStopWord("ones");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(364);
		tempStop.setStopWord("one\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(365);
		tempStop.setStopWord("only");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(366);
		tempStop.setStopWord("onto");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(367);
		tempStop.setStopWord("opposite");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(368);
		tempStop.setStopWord("or");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(369);
		tempStop.setStopWord("other");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(370);
		tempStop.setStopWord("others");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(371);
		tempStop.setStopWord("otherwise");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(372);
		tempStop.setStopWord("ought");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(373);
		tempStop.setStopWord("oughtn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(374);
		tempStop.setStopWord("our");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(375);
		tempStop.setStopWord("ours");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(376);
		tempStop.setStopWord("ourselves");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(377);
		tempStop.setStopWord("out");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(378);
		tempStop.setStopWord("outside");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(379);
		tempStop.setStopWord("over");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(380);
		tempStop.setStopWord("overall");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(381);
		tempStop.setStopWord("own");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(382);
		tempStop.setStopWord("particular");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(383);
		tempStop.setStopWord("particularly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(384);
		tempStop.setStopWord("past");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(385);
		tempStop.setStopWord("per");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(386);
		tempStop.setStopWord("perhaps");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(387);
		tempStop.setStopWord("placed");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(388);
		tempStop.setStopWord("please");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(389);
		tempStop.setStopWord("plus");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(390);
		tempStop.setStopWord("possible");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(391);
		tempStop.setStopWord("presumably");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(392);
		tempStop.setStopWord("probably");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(393);
		tempStop.setStopWord("provided");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(394);
		tempStop.setStopWord("provides");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(395);
		tempStop.setStopWord("que");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(396);
		tempStop.setStopWord("quite");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(397);
		tempStop.setStopWord("qv");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(398);
		tempStop.setStopWord("rather");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(399);
		tempStop.setStopWord("rd");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(400);
		tempStop.setStopWord("re");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(401);
		tempStop.setStopWord("really");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(402);
		tempStop.setStopWord("reasonably");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(403);
		tempStop.setStopWord("recent");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(404);
		tempStop.setStopWord("recently");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(405);
		tempStop.setStopWord("regarding");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(406);
		tempStop.setStopWord("regardless");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(407);
		tempStop.setStopWord("regards");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(408);
		tempStop.setStopWord("relatively");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(409);
		tempStop.setStopWord("respectively");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(410);
		tempStop.setStopWord("right");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(411);
		tempStop.setStopWord("round");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(412);
		tempStop.setStopWord("said");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(413);
		tempStop.setStopWord("same");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(414);
		tempStop.setStopWord("saw");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(415);
		tempStop.setStopWord("say");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(416);
		tempStop.setStopWord("saying");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(417);
		tempStop.setStopWord("says");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(418);
		tempStop.setStopWord("second");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(419);
		tempStop.setStopWord("secondly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(420);
		tempStop.setStopWord("see");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(421);
		tempStop.setStopWord("seeing");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(422);
		tempStop.setStopWord("seem");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(423);
		tempStop.setStopWord("seemed");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(424);
		tempStop.setStopWord("seeming");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(425);
		tempStop.setStopWord("seems");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(426);
		tempStop.setStopWord("seen");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(427);
		tempStop.setStopWord("self");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(428);
		tempStop.setStopWord("selves");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(429);
		tempStop.setStopWord("sensible");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(430);
		tempStop.setStopWord("sent");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(431);
		tempStop.setStopWord("serious");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(432);
		tempStop.setStopWord("seriously");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(433);
		tempStop.setStopWord("seven");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(434);
		tempStop.setStopWord("several");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(435);
		tempStop.setStopWord("shall");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(436);
		tempStop.setStopWord("shan\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(437);
		tempStop.setStopWord("she");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(438);
		tempStop.setStopWord("she\'d");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(439);
		tempStop.setStopWord("she\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(440);
		tempStop.setStopWord("she\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(441);
		tempStop.setStopWord("should");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(442);
		tempStop.setStopWord("shouldn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(443);
		tempStop.setStopWord("since");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(444);
		tempStop.setStopWord("six");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(445);
		tempStop.setStopWord("so");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(446);
		tempStop.setStopWord("some");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(447);
		tempStop.setStopWord("somebody");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(448);
		tempStop.setStopWord("someday");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(449);
		tempStop.setStopWord("somehow");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(450);
		tempStop.setStopWord("someone");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(451);
		tempStop.setStopWord("something");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(452);
		tempStop.setStopWord("sometimes");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(453);
		tempStop.setStopWord("sometime");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(454);
		tempStop.setStopWord("somewhat");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(455);
		tempStop.setStopWord("somewhere");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(456);
		tempStop.setStopWord("soon");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(457);
		tempStop.setStopWord("sorry");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(458);
		tempStop.setStopWord("specified");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(459);
		tempStop.setStopWord("specify");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(460);
		tempStop.setStopWord("specifying");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(461);
		tempStop.setStopWord("still");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(462);
		tempStop.setStopWord("sub");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(463);
		tempStop.setStopWord("such");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(464);
		tempStop.setStopWord("sup");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(465);
		tempStop.setStopWord("sure");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(466);
		tempStop.setStopWord("take");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(467);
		tempStop.setStopWord("taken");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(468);
		tempStop.setStopWord("taking");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(469);
		tempStop.setStopWord("tell");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(470);
		tempStop.setStopWord("tends");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(471);
		tempStop.setStopWord("th");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(472);
		tempStop.setStopWord("than");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(473);
		tempStop.setStopWord("thank");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(474);
		tempStop.setStopWord("thanks");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(475);
		tempStop.setStopWord("thanx");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(476);
		tempStop.setStopWord("that");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(477);
		tempStop.setStopWord("that\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(478);
		tempStop.setStopWord("thats");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(479);
		tempStop.setStopWord("that\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(480);
		tempStop.setStopWord("that\'ve");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(481);
		tempStop.setStopWord("the");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(482);
		tempStop.setStopWord("their");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(483);
		tempStop.setStopWord("theirs");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(484);
		tempStop.setStopWord("them");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(485);
		tempStop.setStopWord("themselves");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(486);
		tempStop.setStopWord("then");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(487);
		tempStop.setStopWord("thence");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(488);
		tempStop.setStopWord("there");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(489);
		tempStop.setStopWord("thereafter");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(490);
		tempStop.setStopWord("thereby");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(491);
		tempStop.setStopWord("there\'d");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(492);
		tempStop.setStopWord("therefore");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(493);
		tempStop.setStopWord("therein");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(494);
		tempStop.setStopWord("there\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(495);
		tempStop.setStopWord("there\'re");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(496);
		tempStop.setStopWord("thereupon");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(497);
		tempStop.setStopWord("there\'ve");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(498);
		tempStop.setStopWord("these");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(499);
		tempStop.setStopWord("they");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(500);
		tempStop.setStopWord("they\'d");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(501);
		tempStop.setStopWord("they\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(502);
		tempStop.setStopWord("they\'re");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(503);
		tempStop.setStopWord("they\'ve");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(504);
		tempStop.setStopWord("thing");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(505);
		tempStop.setStopWord("things");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(506);
		tempStop.setStopWord("think");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(507);
		tempStop.setStopWord("third");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(508);
		tempStop.setStopWord("thirty");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(509);
		tempStop.setStopWord("this");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(510);
		tempStop.setStopWord("thorough");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(511);
		tempStop.setStopWord("thoroughly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(512);
		tempStop.setStopWord("those");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(513);
		tempStop.setStopWord("though");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(514);
		tempStop.setStopWord("three");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(515);
		tempStop.setStopWord("through");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(516);
		tempStop.setStopWord("throughout");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(517);
		tempStop.setStopWord("thru");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(518);
		tempStop.setStopWord("thus");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(519);
		tempStop.setStopWord("till");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(520);
		tempStop.setStopWord("to");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(521);
		tempStop.setStopWord("together");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(522);
		tempStop.setStopWord("too");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(523);
		tempStop.setStopWord("took");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(524);
		tempStop.setStopWord("toward");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(525);
		tempStop.setStopWord("towards");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(526);
		tempStop.setStopWord("tried");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(527);
		tempStop.setStopWord("tries");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(528);
		tempStop.setStopWord("truly");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(529);
		tempStop.setStopWord("try");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(530);
		tempStop.setStopWord("trying");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(531);
		tempStop.setStopWord("t\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(532);
		tempStop.setStopWord("twice");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(533);
		tempStop.setStopWord("two");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(534);
		tempStop.setStopWord("un");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(535);
		tempStop.setStopWord("under");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(536);
		tempStop.setStopWord("underneath");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(537);
		tempStop.setStopWord("undoing");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(538);
		tempStop.setStopWord("unfortunately");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(539);
		tempStop.setStopWord("unless");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(540);
		tempStop.setStopWord("unlike");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(541);
		tempStop.setStopWord("unlikely");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(542);
		tempStop.setStopWord("until");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(543);
		tempStop.setStopWord("unto");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(544);
		tempStop.setStopWord("up");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(545);
		tempStop.setStopWord("upon");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(546);
		tempStop.setStopWord("upwards");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(547);
		tempStop.setStopWord("us");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(548);
		tempStop.setStopWord("use");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(549);
		tempStop.setStopWord("used");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(550);
		tempStop.setStopWord("useful");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(551);
		tempStop.setStopWord("uses");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(552);
		tempStop.setStopWord("using");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(553);
		tempStop.setStopWord("usually");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(554);
		tempStop.setStopWord("v");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(555);
		tempStop.setStopWord("value");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(556);
		tempStop.setStopWord("various");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(557);
		tempStop.setStopWord("versus");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(558);
		tempStop.setStopWord("very");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(559);
		tempStop.setStopWord("via");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(560);
		tempStop.setStopWord("viz");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(561);
		tempStop.setStopWord("vs");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(562);
		tempStop.setStopWord("want");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(563);
		tempStop.setStopWord("wants");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(564);
		tempStop.setStopWord("was");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(565);
		tempStop.setStopWord("wasn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(566);
		tempStop.setStopWord("way");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(567);
		tempStop.setStopWord("we");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(568);
		tempStop.setStopWord("we\'d");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(569);
		tempStop.setStopWord("welcome");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(570);
		tempStop.setStopWord("well");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(571);
		tempStop.setStopWord("we\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(572);
		tempStop.setStopWord("went");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(573);
		tempStop.setStopWord("were");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(574);
		tempStop.setStopWord("we\'re");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(575);
		tempStop.setStopWord("weren\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(576);
		tempStop.setStopWord("we\'ve");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(577);
		tempStop.setStopWord("what");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(578);
		tempStop.setStopWord("whatever");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(579);
		tempStop.setStopWord("what\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(580);
		tempStop.setStopWord("what\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(581);
		tempStop.setStopWord("what\'ve");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(582);
		tempStop.setStopWord("when");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(583);
		tempStop.setStopWord("whence");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(584);
		tempStop.setStopWord("whenever");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(585);
		tempStop.setStopWord("where");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(586);
		tempStop.setStopWord("whereafter");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(587);
		tempStop.setStopWord("whereas");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(588);
		tempStop.setStopWord("whereby");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(589);
		tempStop.setStopWord("wherein");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(590);
		tempStop.setStopWord("where\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(591);
		tempStop.setStopWord("whereupon");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(592);
		tempStop.setStopWord("wherever");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(593);
		tempStop.setStopWord("whether");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(594);
		tempStop.setStopWord("which");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(595);
		tempStop.setStopWord("whichever");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(596);
		tempStop.setStopWord("while");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(597);
		tempStop.setStopWord("whilst");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(598);
		tempStop.setStopWord("whither");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(599);
		tempStop.setStopWord("who");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(600);
		tempStop.setStopWord("who\'d");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(601);
		tempStop.setStopWord("whoever");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(602);
		tempStop.setStopWord("whole");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(603);
		tempStop.setStopWord("who\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(604);
		tempStop.setStopWord("whom");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(605);
		tempStop.setStopWord("whomever");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(606);
		tempStop.setStopWord("who\'s");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(607);
		tempStop.setStopWord("whose");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(608);
		tempStop.setStopWord("why");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(609);
		tempStop.setStopWord("will");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(610);
		tempStop.setStopWord("willing");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(611);
		tempStop.setStopWord("wish");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(612);
		tempStop.setStopWord("with");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(613);
		tempStop.setStopWord("within");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(614);
		tempStop.setStopWord("without");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(615);
		tempStop.setStopWord("wonder");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(616);
		tempStop.setStopWord("won\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(617);
		tempStop.setStopWord("wouldn\'t");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(618);
		tempStop.setStopWord("yes");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(619);
		tempStop.setStopWord("yet");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(620);
		tempStop.setStopWord("you");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(621);
		tempStop.setStopWord("you\'d");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(622);
		tempStop.setStopWord("you\'ll");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(623);
		tempStop.setStopWord("your");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(624);
		tempStop.setStopWord("you\'re");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(625);
		tempStop.setStopWord("yours");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(626);
		tempStop.setStopWord("yourself");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(627);
		tempStop.setStopWord("yourselves");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(628);
		tempStop.setStopWord("you\'ve");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(629);
		tempStop.setStopWord("zero");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(630);
		tempStop.setStopWord("harry");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(631);
		tempStop.setStopWord("potter");
		stopWords.add(tempStop);
		tempStop = new StopWord();
		tempStop.setStopWordId(632);
		tempStop.setStopWord("filch");
		stopWords.add(tempStop);
		stopWords.trimToSize();
	}
	
	@Override
	public List<StopWord> getStopWordsList() {
		return stopWords;
	}

	@Override
	public List<String> getStopWordStrings() {
		List<String> stopWordString = new ArrayList<String>();
		
		for (StopWord stopWord : stopWords) {
			stopWordString.add(stopWord.getStopWord());
		}
		
		return stopWordString;
	}

	@Override
	public StopWord getStopWordById(int stopWordId) {
		for (StopWord stopWord : stopWords) {
			if (stopWord.getStopWordId() == stopWordId) {
				return stopWord;
			}
		}
		
		return null;
	}

}
